apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: zyzornatti/udagram-api-user:v2
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m        
        envFrom:
          - configMapRef:
              name: udagram-env
          - secretRef:
              name: udagramdb-env
        volumeMounts:
          - mountPath: "/root/.aws/"
            name: udagram-aws-env
      volumes:
        - name: udagram-aws-env
          configMap: 
            name: udagram-env